version: '3.8'

services:
  express-app:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
